name: CI

on:
  push:
    branches: [main]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mizchi/pkfire@6e8f4735acd74407455ee6be3debfe9ca8c8e4e9
      - run: pkl --version
